"""Anchor pool: cross-linguistic onomatopoeia for Stage 6 phonology.

Parallel workstream to the SAE pipeline (Stages 1-5). Collects native-language
onomatopoeic forms for a fixed concept inventory, normalizes to IPA, and emits
a clean `(concept, language, orthography, ipa, source, ...)` table. The output
plugs into Stage 6 where phonology is generated by Sibson interpolation in
semantic space, with anchors weighted by their cross-linguistic signature.

Sketch + plan in repo root: anchor-pool-sketch.md, anchor-data-plan.md.

Storage is on the fauna NVMe, separate from the SAE pipeline's data/ tree.
"""

from __future__ import annotations

from pathlib import Path

ANCHOR_ROOT: Path = Path("/media/menser/fauna/interlingua/anchoring")
ANCHOR_RAW: Path = ANCHOR_ROOT / "raw"
ANCHOR_INTERIM: Path = ANCHOR_ROOT / "interim"
ANCHOR_PROCESSED: Path = ANCHOR_ROOT / "processed"
